### ISSUE TITLE
clang11 problem

### ISSUE THREAD

**Issue by spidunno** [Morglod/bun-ffi-gen#3]
I tried the example given in the readme with the latest version of wgpu-native for the github page for it, it seems to create an error with one of the structs and tries to run c code containing `sizeof(undefined)`. not sure how to really fix this

**Comment by Morglod** [comment]
Hi! Will check it

What system & compiler version you have?

**Comment by spidunno** [comment]
I'm on Ubuntu (WSL) and clang --version reads

```
Ubuntu clang version 11.0.0-2~ubuntu20.04.1
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```
here is my wgpu.h (github doesn't support .h files so I uploaded it to a file server) https://ninja.dog/1B71ry.h

**Comment by Morglod** [comment]
For me everything works (both with latest wgpu-native & yours wgpu.h)
clang13, macos

Could you provide some logs or investigate with which struct error happens?

Here is my result (you should adjust `_LIB_PATH` variable inside it):
[wgpu.ts.zip](https://github.com/Morglod/bun-ffi-gen/files/15404927/wgpu.ts.zip)
